[31mmkdir: path already exists: .secrets[39m
{"@timestamp":"2025-02-22T21:44:23.817Z","ecs.version":"8.10.0","log.level":"info","message":""}
Error
    at <anonymous> (/Users/andrewsmith/developer/repos/home-automation/packages/shell-utils/src/throwIfError.ts:42:18)
    at <anonymous> (/Users/andrewsmith/developer/repos/home-automation/packages/env-utils/src/utils.ts:5:17)
    at <anonymous> (/Users/andrewsmith/developer/repos/home-automation/packages/shell-utils/src/throwIfError.ts:40:36)
    at new Promise (<anonymous>)
    at throwIfError (/Users/andrewsmith/developer/repos/home-automation/packages/shell-utils/src/throwIfError.ts:18:3)
    at Object.run [90m(/Users/andrewsmith/developer/repos/home-automation/apps/pihole/[39mscripts/deploy.ts:47:11[90m)[39m
    at async executor (/Users/andrewsmith/developer/repos/home-automation/packages/nx-executors/dist/invoke.js:18404:5)
    at async promiseToIterator (/Users/andrewsmith/developer/repos/home-automation/.yarn/unplugged/nx-virtual-32d499b082/node_modules/[4mnx[24m/src/command-line/run/run.js:36:11)
    at async getLastValueFromAsyncIterableIterator (/Users/andrewsmith/developer/repos/home-automation/.yarn/unplugged/nx-virtual-32d499b082/node_modules/[4mnx[24m/src/utils/async-iterator.js:15:19)
    at async iteratorToProcessStatusCode (/Users/andrewsmith/developer/repos/home-automation/.yarn/unplugged/nx-virtual-32d499b082/node_modules/[4mnx[24m/src/command-line/run/run.js:39:25)
1350cf07-236f-4ad2-8e72-e50072e75830
d81721c1-c63b-4576-817d-1f8fa6e43a49
2442cad2-90ec-428e-be1a-3fa5c4b56ab6
6361f43d-9f33-4c45-b22c-1aa28e40616c
service/pihole1 configured
service/pihole2 configured
endpoints/pihole1 unchanged
endpoints/pihole2 unchanged
